#pragma once

#cmakedefine CONFIG_LIBC_INCLUDE_DIRECTORY "${CONFIG_LIBC_INCLUDE_DIRECTORY}"
#cmakedefine CONFIG_GNU_TOOLS_ROOT         "${CONFIG_GNU_TOOLS_ROOT}"
#cmakedefine CONFIG_GNU_TOOLS_GCC_EXE      "${CONFIG_GNU_TOOLS_GCC_EXE}"